@baseUrl = http://localhost:3333

###

# @name request_access
POST {{baseUrl}}/access-requests
Content-Type: application/json

{
  "message": "Me responde apenas com 'ok' nada mais do que isso, apenas uma resposta curta"
}
