services:
  postgres:
    image: postgres
    container_name: cloud-gatekeeper
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cloud-gatekeeper
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
    name: cloud-gatekeeper_network

